In [1]:
import torchvision.models as models
import torch.nn as nn
import torch
import os
import cv2
from PIL import Image 
import glob
import torchvision
import torchvision.transforms as transforms
import datetime
import numpy as np
import torch.nn.functional as F
import matplotlib.pyplot as plt
import matplotlib
from torchvision.utils import make_grid, save_image



from Grad_CAM.img_norm import Normalize, transform_img
from Grad_CAM.model_value import mv

In [2]:
use_pretrained=True # 학습 된 파라미터 사용
net = models.vgg16(pretrained=use_pretrained).cuda()

# 모델 네트워크 구성 출력
print(net)

c:\Users\mjy22\anaconda3\envs\pytorch\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
c:\Users\mjy22\anaconda3\envs\pytorch\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [3]:
for i in net._modules.items():
    print(i[0])
    

features
avgpool
classifier


In [4]:
net._modules.keys()

odict_keys(['features', 'avgpool', 'classifier'])

In [5]:
def norm_preprocess(img_pth,means,stds): # img_pth 주면 img -> torch tensor type (1,3,224,224) 
    # means = [r,g,b] / std = [r,g,b]
    p_img = Image.open(img_pth) 
    tensor_img = torch.from_numpy(np.asarray(p_img)).permute(2,0,1).unsqueeze(0).float().div(255).cuda()
    # vgg -> 1,3,224,224
    # alex -> 1,3,227,227
    if tensor_img != (1,3,224,224) :
        tensor_img = F.interpolate(tensor_img,size=(224,224),mode='bilinear', align_corners=False)

    norm_mean_std = Normalize(mean=means, std=stds)
    nt_img = norm_mean_std(tensor_img)

    return nt_img , tensor_img

In [6]:
# !wget https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt

In [7]:
label_list = [] 
f = open('./imagenet_classes.txt','r')
while True:
    line = f.readline()
    if not line: break
    label_list.append(line.split('\n')[0])
f.close()

len(label_list)


1000

In [8]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
img_pth = glob.glob('./car_data/test_data/*.jpg')
model_pth = glob.glob('./vgg_pt/*pt')
save_pth = './car_data/grad_cam_result/vgg_pt/sportcar/'
label_idx = 817
print(img_pth[0])


./car_data/test_data\000099.jpg


In [9]:
for i in img_pth:
    name = i.split('/')[2].split('\\')[1].split('.')[0] # .split('/')[3]
    img,origin_img = norm_preprocess(i,means=[0.485, 0.456, 0.406], stds=[0.229, 0.224, 0.225])
    grad_cam = mv('features',net,img,origin_img,label_idx,name,save_pth,label_list)
    grad_cam_map, predic_idx,predic_cls = grad_cam.make_img()
    if label_idx != predic_idx: 
        save_path = './car_data/grad_cam_result/vgg_pt/False_result'
        print('-------'*3)
        print(i)
        print(predic_idx)
        print(predic_cls)
        grads_cam = mv('features',net,img,origin_img,predic_idx,name,save_path,label_list,re=True)
        a,b,c= grads_cam.make_img()


C:\Users\mjy22\AppData\Local\Temp\ipykernel_18920\3694273873.py:4: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_numpy.cpp:178.)
  tensor_img = torch.from_numpy(np.asarray(p_img)).permute(2,0,1).unsqueeze(0).float().div(255).cuda()
c:\Users\mjy22\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py:1053: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full

---------------------
./car_data/test_data\000099.jpg
436
beach wagon
---------------------
./car_data/test_data\000101.jpg
656
minivan
---------------------
./car_data/test_data\000141.jpg
656
minivan
---------------------
./car_data/test_data\000143.jpg
436
beach wagon
---------------------
./car_data/test_data\000152.jpg
656
minivan
---------------------
./car_data/test_data\000153.jpg
436
beach wagon
---------------------
./car_data/test_data\000154.jpg
436
beach wagon
---------------------
./car_data/test_data\000194.jpg
656
minivan
---------------------
./car_data/test_data\000851.jpg
882
vacuum
---------------------
./car_data/test_data\001097.jpg
479
car wheel
---------------------
./car_data/test_data\001221.jpg
436
beach wagon
---------------------
./car_data/test_data\001273.jpg
436
beach wagon
---------------------
./car_data/test_data\001688.jpg
882
vacuum
---------------------
./car_data/test_data\001883.jpg
656
minivan
---------------------
./car_data/test_data\001958.jp

In [10]:
htmap = grad_cam_map # 1,1,224,224 tensor gpu 

htmap_np=htmap.cpu().numpy() # 1,1,224,224 numpy 

htmap_np_sqeeze = htmap_np.squeeze() # 224,224 numpy -> fromarray 

print(htmap_np_sqeeze.shape)

htmap_np_sqeeze



(224, 224)


array([[0.01262219, 0.01262219, 0.01262219, ..., 0.28693682, 0.28693682,
        0.28693682],
       [0.01262219, 0.01262219, 0.01262219, ..., 0.28693682, 0.28693682,
        0.28693682],
       [0.01262219, 0.01262219, 0.01262219, ..., 0.28693682, 0.28693682,
        0.28693682],
       ...,
       [0.4222462 , 0.4222462 , 0.4222462 , ..., 0.26425016, 0.26425016,
        0.26425016],
       [0.4222462 , 0.4222462 , 0.4222462 , ..., 0.26425016, 0.26425016,
        0.26425016],
       [0.4222462 , 0.4222462 , 0.4222462 , ..., 0.26425016, 0.26425016,
        0.26425016]], dtype=float32)

In [11]:
htmap_np_img = Image.fromarray(htmap_np)


TypeError: Cannot handle this data type: (1, 1, 224, 224), <f4

In [12]:
onetake = grad_cam_map.squeeze()
onetake.shape


torch.Size([224, 224])

In [13]:
onetake.mean()


tensor(0.3131, device='cuda:0')

In [14]:
onetake.std() 

tensor(0.1992, device='cuda:0')

In [45]:
heatmap_gray = onetake

heatmap_gray_np= heatmap_gray.cpu()
print(heatmap_gray_np.mean())
print(heatmap_gray_np.std())

print(heatmap_gray_np.shape)

ht_np = np.uint8(heatmap_gray_np*255)

print(ht_np)

cv2.imshow('result',ht_np)
cv2.waitKey()
cv2.destroyAllWindows()


tensor(0.3131)
tensor(0.1992)
torch.Size([224, 224])
[[  3   3   3 ...  73  73  73]
 [  3   3   3 ...  73  73  73]
 [  3   3   3 ...  73  73  73]
 ...
 [107 107 107 ...  67  67  67]
 [107 107 107 ...  67  67  67]
 [107 107 107 ...  67  67  67]]


In [17]:
tensor1 = torch.ones(1,1,4,4)
print(tensor1)

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])


In [27]:
tensor1_255 = 255*tensor1.squeeze()
print(type(tensor1_255))
print(tensor1_255.shape)
tensor1_255


<class 'torch.Tensor'>
torch.Size([4, 4])


tensor([[255., 255., 255., 255.],
        [255., 255., 255., 255.],
        [255., 255., 255., 255.],
        [255., 255., 255., 255.]])

In [31]:
tensor1_255_np = np.uint8(tensor1_255)

print(type(tensor1_255_np))
print(tensor1_255_np.shape)
tensor1_255_np

<class 'numpy.ndarray'>
(4, 4)


array([[255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255]], dtype=uint8)

In [35]:
cv2.imshow('testimg',tensor1_255_np)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
from PIL import Image


seg_img_pix = Image.open('./car_data/segmentation/002211.jpg')

seg_img = torch.from_numpy(np.asarray(seg_img_pix)).permute(2,0,1).float()

seg_img.shape


torch.Size([3, 224, 224])

In [ ]:
seg_img[1].shape

torch.Size([224, 224])

In [ ]:
# import os 
# import glob
# import numpy as np 
# grad_cam_list = [] 
# text_dir = glob.glob('./txt_result_grad_cam/*.txt')
# for i in text_dir:
#     f = open(i,'r')
    
#     grad_cam_list.append(f.read())
# f.close()

In [ ]:
np.asarray(grad_cam_list).shape

(24,)

In [ ]:
np.asarray(grad_cam_list)

array(['[[0.         0.         0.         ... 0.00500743 0.00500743 0.00500743]\n [0.         0.         0.         ... 0.00500743 0.00500743 0.00500743]\n [0.         0.         0.         ... 0.00500743 0.00500743 0.00500743]\n ...\n [0.24338633 0.24338633 0.24338633 ... 0.188556   0.188556   0.188556  ]\n [0.24338633 0.24338633 0.24338633 ... 0.188556   0.188556   0.188556  ]\n [0.24338633 0.24338633 0.24338633 ... 0.188556   0.188556   0.188556  ]]',
       '[[0.34243792 0.34243792 0.34243792 ... 0.2134192  0.2134192  0.2134192 ]\n [0.34243792 0.34243792 0.34243792 ... 0.2134192  0.2134192  0.2134192 ]\n [0.34243792 0.34243792 0.34243792 ... 0.2134192  0.2134192  0.2134192 ]\n ...\n [0.26394114 0.26394114 0.26394114 ... 0.195671   0.195671   0.195671  ]\n [0.26394114 0.26394114 0.26394114 ... 0.195671   0.195671   0.195671  ]\n [0.26394114 0.26394114 0.26394114 ... 0.195671   0.195671   0.195671  ]]',
       '[[0.41637635 0.41637635 0.41637635 ... 0.         0.         0.        ]